#!/bin/bash
#SBATCH --time=1:00:00
#SBATCH --nodes=1 
#SBATCH --ntasks-per-node=48
#SBATCH --mem=384000
#SBATCH --job-name=MoS2
#SBATCH --mail-type=END
#SBATCH --account=ACCOUNT
#SBATCH --mail-user=EMAIL@mail.com
#SBATCH --error=error.txt
#SBATCH --output=output.txt
 
module load espresso

export MV2_ENABLE_AFFINITY=0 
export I_MPI_PIN_DOMAIN=auto 
export I_MPI_PIN_ORDER=bunch 
export KMP_AFFINITY=compact,granularity=fine,1 
export OMP_NUM_THREADS=1

echo "SLURM_NTASKS_PER_NODE = $SLURM_NTASKS_PER_NODE" 
echo "SLURM_JOB_NUM_NODES   = $SLURM_JOB_NUM_NODES" 
echo "OMP_NUM_THREADS       = $OMP_NUM_THREADS"

PPN=$(( $SLURM_NTASKS_PER_NODE * $SLURM_JOB_NUM_NODES / $OMP_NUM_THREADS ))
echo "PPN = $PPN"

### Quantum Espresso:
mpirun -np $PPN pw.x -ni 1 -nk 2 -nt 2 -nd 1 -nb 2 -input scf.in > scf.out

