#!/bin/bash
#SBATCH --time=1:00:00
#SBATCH --nodes=1 
#SBATCH --ntasks-per-node=48
#SBATCH --job-name=GaSe_orbitals
#SBATCH --mail-type=END,FAIL
#SBATCH --account=<ACCOUNT>
#SBATCH --mail-user=<EMAIL>
#SBATCH --error=error.txt
#SBATCH --output=output.txt
 
module load espresso/espresso-6.6-mvapich2-2.3.1-ic-2019.3.199


export MV2_ENABLE_AFFINITY=0 
export I_MPI_PIN_DOMAIN=auto 
export I_MPI_PIN_ORDER=bunch 
export KMP_AFFINITY=compact,granularity=fine,1 
export OMP_NUM_THREADS=1

PPN=$(( $SLURM_TASKS_PER_NODE / $OMP_NUM_THREADS ))
echo "PPN = $PPN"

### Quantum Espresso:
mpirun -ppn $PPN pw.x -ni 1 -nk 2  -nt 2 -nd 1 -nb 2 -input scf.in  > scf.out
mpirun -ppn $PPN pw.x -ni 1 -nk 2  -nt 2 -nd 1 -nb 2 -input scf2.in  > scf2.out
mpirun -ppn $PPN pw.x -ni 1 -nk 2  -nt 2 -nd 1 -nb 2 -input scf3.in  > scf3.out

### PDOS 
mpirun   -ppn $PPN projwfc.x < kpdos.in > kpdos.out

### Quantum Espresso Band structure:
mpirun -ppn $PPN pw.x -ni 1 -nk 24 -nt 1 -nd 1 -nb 1 < bands.in > bands.out
mpirun -ppn $PPN bands.x < bandsx.in > bandsx.out


 




